project:
  type: book
  output-dir: docs
  
book:
  title: Social Networks
  subtitle: An Introduction
  author: Omar Lizardo and Isaac Jilbert
  date: 1/15/2023
  repo-url: https://github.com/olizardo/networks-textbook
  repo-actions: [source]
  search:
    location: sidebar
    type: textbox
  navbar:
    pinned: true
    background: "#2D68C4"
  sidebar: 
    logo: social-ties1.jpeg
    subtitle: Lessons
  page-navigation: true
  page-footer: "Copyright 2023, Omar Lizardo & Isaac Jilbert" 
  chapters:
    - index.qmd
    - part: "Introduction to Networks"
      chapters:
      - lesson-theory-what-are-networks.qmd
      - lesson-theory-what-are-social-networks.qmd
    - part: "Graph Theory: The Basics"
      chapters:
      - lesson-graphs-theory.qmd
      - lesson-graphs-subgraphs.qmd
      - lesson-theory-types.qmd
      - lesson-graphs-ties.qmd
      - lesson-graphs-metrics.qmd
      - lesson-graphs-neighborhoods.qmd
      - lesson-graphs-degree.qmd
      - lesson-graphs-degree-metrics.qmd
      - lesson-graphs-paths.qmd
      - lesson-graphs-directed-paths.qmd
      - lesson-graphs-connectivity.qmd
    - part: "Matrices: The Basics"
      chapters:
      - lesson-matrix-intro.qmd
      - lesson-matrix-adjacency.qmd
      - lesson-matrix-row-column-sums.qmd
      - lesson-matrix-operations.qmd
      - lesson-matrix-multiplication.qmd
    - part: "Centrality"
      chapters:
      - lesson-sna-degree-centrality.qmd
      - lesson-sna-closeness.qmd
      - lesson-sna-betweenness.qmd
      - lesson-sna-bigthree.qmd
    - part: "Prestige"
      chapters:
      - lesson-sna-eigenvector.qmd
      #- lesson-sna-hubs-and-authorities.qmd
      #- lesson-sna-status.qmd
    - part: "Two-Mode Networks"
      chapters:
      - lesson-sna-affiliation-networks.qmd
    - part: "Ego Networks"
      chapters:
      - lesson-sna-ego-networks.qmd
      - lesson-sna-ego-collect.qmd
      - lesson-theory-ego-homo.qmd
    - part: "Subgroups and Blocks"
      chapters:
      - lesson-sna-groups-cliques.qmd
      - lesson-theory-equivalence.qmd
      - lesson-sna-local-similarity.qmd
    - part: "Network Theory"
      chapters:
      - lesson-theory-dunbar.qmd
      - lesson-theory-swt.qmd
      - lesson-theory-sht.qmd
      - lesson-theory-smt.qmd
      - lesson-theory-dyadic-balance.qmd
      - lesson-theory-triadic-balance.qmd
      - lesson-theory-structural-balance.qmd
      - lesson-theory-valenced-interactions.qmd
      - lesson-theory-hierarchies.qmd
      - lesson-theory-diffusion.qmd
      - lesson-theory-small-world.qmd

bibliography: networks.bib

format:
  html:
    css: styles.css
    page-layout: full
    theme:
      light: flatly
      dark: darkly    
    toc: true
    linkcolor: "#ff7e26;"
    
execute:
  echo: false
  warning: false
  message: false
  freeze: auto

editor: source

